# **Pandas Learning **

# **Identify dates which show a greater likelihood of cyclone**

# **Instructions**

Problem Statement

Write Python code using Pandas to identify dates which show a greater likelihood of cyclone. Cyclone likelihood is defined as high if the temperature, humidity, and windspeed values are respectively greater than some threshold value. Note that all three conditions must be true to declare a high likelihood of cyclone. Your code must print the dates with high likelihood or must print that there is low cyclone likelihood.



Data Description

The dataset is a CSV file with 10 entries. Each entry records the temperature, humidity, and windspeed levels on a certain date. The column names are Date, Temperature (°C), Humidity (%), WindSpeed (km/h), and the data types of their respective entries are str, float, float, float. The data does not have any missing values. Row indices are default integer indices.



Input Format

The temperature, humidity, and windspeed threshold separated by commas



Output Format

A string mentioning the dates of high likelihood of cyclone



Sample Case 1 Input

20, 60, 10

# **Sample Case 1 Output**

High Cyclone Likelihood Dates: 09-01-2024, 08-01-2024, 07-01-2024, 06-01-2024, 05-01-2024, 04-01-2024, 01-01-2024,



Sample Case 2 Input

23, 70, 26

Sample Case 2 Output

Low Likelihood



Constraints

Unrealistic values (negative numbers, non-numerics, and so on) of temperature, humidity, and windspeed are not accounted for
Input string is processed as a tuple of three values in the order temperature, humidity, windspeed

In [ ]:
# Do not edit this data and input-output processing section
import pandas as pd
import ast
df = pd.read_csv('https://d3ejq4mxgimsmf.cloudfront.net/daily_weather_records_data-413ee6bcc12441bb89e0a8dbb048b639.csv')

input_params = ast.literal_eval(input())

# Write your code here

ser_out = df[(df['Temperature (°C)'] > input_params[0]) & (df['Humidity (%)'] > input_params[1]) & (df['WindSpeed (km/h)'] > input_params[2])]['Date'].tolist()

# Do not edit this input-output processing section
if len(ser_out) == 0: print('Low Likelihood')
else:
    out_str = ''
    for val in ser_out:
        out_str = str(val)+ ', ' + out_str
    print('High Cyclone Likelihood Dates: ' + out_str)

20, 60, 10
High Cyclone Likelihood Dates: 09-01-2024, 08-01-2024, 07-01-2024, 06-01-2024, 05-01-2024, 04-01-2024, 01-01-2024,

# **Calculate the total number of airline passengers for a given year**

# **Instructions**

Problem Statement

Write Python code using Pandas to calculate the total number of airline passengers for a given year. Each entry in the dataset represents the passenger count for a specific month. Your task is to extract the year from the date column, group the monthly passenger values year-wise, and print the total number of passengers for the input year. Remember to first convert the month column into a datetime data type.



Data Description

The dataset is a CSV file containing monthly airline passenger data. There are 144 rows in the dataset. Each row records the date in the format YYYY-MM-DD as a string and the number of passengers for each date. The column names are Month and Passengers, with data types str and int, respectively. The dataset does not have any missing values. Row indices are default integer indices.



Input format

A single integer representing the year

Output format

A single integer representing the total passengers for that year



Sample Case 1 Input

1950

# **Sample Case 1 Output**

1676



Sample Case 2 Input

1953

Sample Case 2 Output

2700



Constraints

The input year must be a valid integer within the dataset range (1949–1960)

Unrealistic or non-numeric values of input are not accounted for

Passenger values are assumed to be valid non-negative integers

In [38]:
# Do not edit this data read section
import pandas as pd
df = pd.read_csv('https://d3ejq4mxgimsmf.cloudfront.net/AirPassengers-d3fb14683f5c47a0bc4b5195bb29677a.csv')

# Write your code here
#ser_out = df.groupby(df['Month'].str[:4])['Passengers'].sum()
df['Month'] = pd.to_datetime(df['Month'])
df['Year'] = df['Month'].dt.year
ser_out = df.groupby('Year')['Passengers'].sum()

# Do not edit this input-output processing section
print(ser_out.loc[int(input())])

1960
5714

In [20]:
df.head(10)

     Month  Passengers
0  1949-01         112
1  1949-02         118
2  1949-03         132
3  1949-04         129
4  1949-05         121
5  1949-06         135
6  1949-07         148
7  1949-08         148
8  1949-09         136
9  1949-10         119

In [31]:
df.iloc[143,:]

Month         1960-12
Passengers        432
Name: 143, dtype: object

In [32]:
df.iloc[df.index[143],:]

Month         1960-12
Passengers        432
Name: 143, dtype: object

In [34]:
df['Year'] = df['Month'].str[:4]
display(df.head())

     Month  Passengers  Year
0  1949-01         112  1949
1  1949-02         118  1949
2  1949-03         132  1949
3  1949-04         129  1949
4  1949-05         121  1949

In [35]:
df.groupby(df['Month'].str[:4])['Passengers'].sum()

Month
1949    1520
1950    1676
1951    2042
1952    2364
1953    2700
1954    2867
1955    3408
1956    3939
1957    4421
1958    4572
1959    5140
1960    5714
Name: Passengers, dtype: int64